# Generated by Django 2.1.5 on 2019-01-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20190113_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawllog',
            name='status',
            field=models.IntegerField(choices=[(1, '성공'), (2, 'github-실패'), (3, 'boj-실패'), (4, '실패')]),
        ),
    ]
